Traceback (most recent call last):
  File "/cbica/home/xjia/.conda/envs/textlearning/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1382, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/cbica/home/xjia/.conda/envs/textlearning/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/cbica/home/xjia/.conda/envs/textlearning/lib/python3.9/site-packages/transformers/trainer_seq2seq.py", line 25, in <module>
    from .trainer import Trainer
  File "/cbica/home/xjia/.conda/envs/textlearning/lib/python3.9/site-packages/transformers/trainer.py", line 207, in <module>
    from accelerate.data_loader import SeedableRandomSampler
ImportError: cannot import name 'SeedableRandomSampler' from 'accelerate.data_loader' (/cbica/home/xjia/.conda/envs/textlearning/lib/python3.9/site-packages/accelerate/data_loader.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs/fs001/cbica/home/xjia/qlora/qlora.py", line 25, in <module>
    from transformers import (
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "/cbica/home/xjia/.conda/envs/textlearning/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1372, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/cbica/home/xjia/.conda/envs/textlearning/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1384, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.trainer_seq2seq because of the following error (look up to see its traceback):
cannot import name 'SeedableRandomSampler' from 'accelerate.data_loader' (/cbica/home/xjia/.conda/envs/textlearning/lib/python3.9/site-packages/accelerate/data_loader.py)
